#' @export
code_orgs <- function(text, code = TRUE, max_count = 1){
  
  if(missing(text)) return(orgRegex)
  
  text <- stringi::stri_trans_general(text,"latin-ascii")
  
  purrr::map_chr(text, function(x) {
    out <- as.data.frame(orgRegex)[
      which(stringi::stri_detect_regex(x, 
                                       unlist(orgRegex[, 3]),
                                       max_count = max_count,
                                       opts_regex = list(case_insensitive = TRUE))),
      ifelse(code, 1, 2)]
    if(length(out)==0) NA_character_ else 
      if(max_count > 1 && length(out)>1) 
        paste0("{",paste(out, collapse = ","),"}") else out
  })
}

# Regex ####
orgRegex <- dplyr::tribble(
  ~orgID, ~Label, #~Regex,
  ## A ####
  "ALAAO","Joint Anti-Locust & Anti-Aviarian Org.",
  "ARICE","Africa Rice Center",
  "APFIC","Asia Pacific Fisheries Comm",
  "ARCAL","Promotion of Nuc. Sci & Tech in L/A",
  "ACPEU","ACP/EU Joint Assembly",                                              
"AFRST","Observatorie economique statistique sub-saharan Afr.",
"ACWL","Advisory Centre on WTO Law",                                       
"AMSC","African/Malgasy Sugar Council",                                   
"ACSO","African Civil Service Observatory",
"AFCI","Afr. Cultural Institute",
"AFDB","African Development Bank",
"AXIB","Afr. Exp/Import Bank",
"AFRND","Afr. Foundation for R & D",
"AFGEC","Afr. Fund Guarantee & Econ. Coop.",
"AFGNC","African Groundnut Council",
"AIPO","African Intellectual Property Organization",
"AMCO","African & Malagasy Coffee Org.",
"AMCOW","African Ministers' Council on Water",
"AOPDA","Afr. Oil Palm Dev. Assoc.",
"AOCRS","Afr. Org. of Cartography & Remote Sensing",
"APPA","African Petroleum Producers Assoc.",
"APTU","African Postal and Telecom Union",
"AFPU","African Postal Union",
"ARIPO","Afr. Regional Intellectual Property Org.",
"ACARE","Africare",
"ASATP","Afr. School of Architec. & Town Planning",
"ASCBC","African Standing Conf. on Biblio. Control",
"ATIMO","African Timber Org.",
"ACPG","ACP Group",
"ALSF","African Legal Support Facility",
"AARO","Afro-Asian Rural Development Org",
"AMIPO","Afro-Malagasy Industrial Property Office",
"AMPTU","Afro-Malagasy Postal and Telecomm Union",
"ACCT","Francophone Agency",
"AITIC","Agency for International Trade Information and Cooperation",
"ASANA","Agency for Safety of Aerial Nav. in Afr. & Madagas.",
"AMCC","Amazonian Coop. Council",
"ACDT","Am Cmte Dependent Territories",
"ANDEC","Andean Community",
"ANDEP","Andean Parliament",
"ANZUS","Australia-NewZealand-US Treaty Organization",
"AAAID","Arab Auth. for Ag. Invest. & Development",
"ABEDA","Arab Bank for Econ. Dev. in Africa",
"ACML","Arab Center for Medical Lit.",
"ABCC","Arab Cooperation Council",
"AFTE","Arab Federation for Technical Educ.",
"AFESD","Arab Fund for Social/Economic Development",
"AGPDO","Arab Gulf Prog. for UN Dev. Org.",
"AIDO","Arab Industrial Devel. & Mining Org.",
"ABIC","Arab Investment Company",
"ABLO","Arab Labor Org.",
"ABMU","Arab Maghreb Union",
"ABMF","Arab Monetary Fund",
"AOAD","Arab Org for Ag. & Develop.",
"AOMR","Arab Org. for Mineral Resources",
"ARPU","Arab Postal Union",
"ARTC","Arctic Council",
"ASEF","Asia-Europe Foundation",
"APCC","Asian/Pacific Coconut Comm.",
"ASPAC","Asia & Pacific Council",
"ASCU","Asian Clearing Union",
"ASDB","Asian Dev. Bank",
"AIDC","Asian Industrial Develop. Council",
"ASPO","Asian Productivity Organization",
"ASRC","Asian Reinsurance Corp.",
"AVRDC","Asian Vegetable Res. & Dev. Center",
"AALCO","Asian-African Legal Consultative Org",
"AOPU","Asian-Oceanic Postal Union",
"APEC","Asia-Pacific Economic Cooperation",
"APIBD","Asia-Pac Instit. for Broadcast Develop.",
"APTC","Asian-Pacific Telecommunity",
"AACB","Assoc. of African Central Banks",
"AATA","Assoc. of African Tax Administrators",
"AATPO","Assoc. of Afr. Trade Promotion Orgs.",
"ACBS","Association of Caribbean States",
"AFSPC","Association of Financial Supervisors of Pacific Countries",
"AIOEC","Assoc. Iron Ore Expt. Countries",
"ARUBB","Association of Rubber Producing States",
"ASEAN","Association of Southeast Asian Nations",
"ATPC","Assoc. Tin Producing Countries",
"AFUN","African Union",
## B ####
"BALC","Baltic Council",
"BALBT","Baltic Batallion",
"BISET","Bank for International Settlements",
"BSEC","Black Sea Economic Council",
"BONN","Bonn Agreement",
"BOTS","Bank of the South",
"BIIEF","Banque Inter'l d'Info. sur les Estats Francophone",
"BOBP","Bay of Bengal Programme Inter-Governmental Organization",
"BENLX","Benelux Community",
"BENIP","Benelux Organization for Intellectual Property",
"BIONT","BIONET",
"BNDP","Board of Nordic Dev. Projects",
"BCSC","British Commonwealth Scientific Comm",
## D ####
"DANUB","Danube Commission",
"DLCEA","Desert Locust Control Org-East Af",
"DEV8","Developing 8 Organization for Economic Cooperation",
"DBGLS","Dev. Bank of Great Lake States",
## E ####
"EAFC","East African Community",
"ENTC","Entente Council",
"ESEAC","Assoc. B/t EEC and States of East Afr. Community",
"EACM","East African Common Market",
"EACSO","East African Common Services Org",
"EADB","East African Development Bank",
"ECCM","East Caribbean Common Market",
"ECCA","Eastern Caribb. Central Bank",
"ECCB","Eastern Caribb. Central Bank",
"ECCAS","Economic Community of Central African States",
"ECWAS","Economic Community of West African States",
"ECOCO","Economic Cooperation Organization",
"ERIA","Economic Research Institute for ASEAN and East Asia",
"EMPMB","Empire Marketing Board",
"EAPO","Eurasian Patent Org.",
"EAEC","Eurasian Economic Community",
"EAPC","Euro-Atlantic Partnership Council",
"EMPPO","Euro & Med Plant Protect Org",
"EUMET","European Association of National Metrology Institute",
"EATOM","European Atomic Energy Agency",
"EBRD","European Bank for Reconstruction & Development",
"EUCB","European Central Bank",
"ECSC","European Coal & Steel Community",
"EUMES","European Collaboration on Measurement Standards",
"EUFMD","Euro Comm for Control Foot-Mouth Disease",
"ECCD","Euro Comm for Control of Danube",
"ECPIF","Euro Company Chem Process Irrad Fuels",
"EFIMA","Euro Comp for Finance Railway Rolling Stock",
"ECPTA","Euro Conf Postal Telecom Admin",
"EFCC","Euro Food Code Council",
"EUEC","European Economic Community",
"EFLWC","Eur. Foundation for Impr. of Living & Work Conditions",
"EFTA","Euro Free Trade Assn",
"EIPCE","European Institute of Peace",
"EIPA","Europ. Institute of Public Admin.",
"EINVB","Euro Investment Bank",
"EMBC","European Molecular Biology Conference",
"EMBL","Eur. Molecular Biol. Lab",
"EMONI","European Monetary Institute",
"EOSAN","Euro Org Safety Air Navig",
"EPTO","European Patent Organization",
"EPAYU","European Payments Union",
"EPFSC","Euro. Postal Financial Services Comm.",
"EPROD","Euro Productivity Agency",
"ESOB","European Southern Observatory",
"ESPA","European Space Agency",
"ESRO","Euro Space Research Org",
"ELDO","Euro Space Vehicle Launcher Dev Org",
"ETRF","European Training Foundation",
"EURO","European Union",
## F ####
"FEAST","Far East Comm",
"FIPLC","Fund 4 Devel. of Indigen Peoples of LA/Carib",
## G ####
"GATT","General Agreement Tariff & Trade",
"GENVF","Global Environ. Fund",
"GHSI","Global Health Security Initiative",
"GRP3","Group of 3",
"GRP15","Group of 15",
"GRP24","Group of 24",
"GRPEO","Group on Earth Observations",
"GBACT","Group on Balkan Agreem. on Coop. on Tourism",
"GRSNC","Guidance Comm. for Road Safety in Nordic Cntry",
"GUCC","Gulf Cooperation Council",
"GOIC","Gulf Org. for Industrial Consulting",
## H ####
"HCPIL","Hague Conf on Private Intl Law",
## J ####
"JINR","Joint Instit for Nuke Research",
## K ####
## L ####
"LCSEC","Group of L/A & Carib. Sugar Exp. Countries",
"LCBC","Lake Chad Basin Comm",
"LCRH","Joint Nordic Org. Lappish Culture & Reindeer",
"LACP","Latin Am Center for Physics",
"LACAC","L/A Civil Aviation Comm.",
"SELA","Latin American Economic System",
"LAIEC","Latin American Institute of Educational Communication",
"LAEO","Latin American Energy Org.",
"LAFDO","L/A Fisheries Devel. Org.",
"LAFTA","Latin American Free Trade Area",
"LAIA","Latin Am Integration Assn",
"LATIN","Latin Union",
"LOAS","League of Arab States",
"LGON","League of Nations",
"LGIDA","Liptako-Gourma Integrated Dev. Auth.",
## M ####
"MANRU","Mano River Union",
"MAOCN","Maritime Analysis and Operations Centre - Narcotics",
"MEDWN","Mediterranean Water Network",
"MCSUR","MERCOSUR",
"MARRI","Migration, Asylum, Refugees Regional Initiative",
"MWCAM","Minist Conf of West & Cent African States on Maritime",
"MPTTC","Multi-Country Posts & Telecomm. Training Center",
"MONTP","Multilat. Fund for the Implement. of the Montreal Protocol",
"MIGA","Multilateral Investment Guarantee Agency",
"MULFO","Multilateral Force Org.",
## N ####
"NAFO","NW Atlantic Fish Org",
"NACAP","Network of Aquaculture Centers in Asia-Pac",
"NGRC","Niger River Comm",
"NALM","Non-Aligned Movement",
"NORVC","Nordic Centre for Welfare and Social Issues",
"NORDC","Nordic Council",
"NCRR","Nord. Council for Reindeer Res.",
"NCTR","Nordic Council for Tax Research",
"NORCM","Nordic Council of Ministers",
"NORDF","Nordic Development Fund",
"NERC","Nordic Econ Res. Council",
"NORIB","Nordic Investment Bank",
"NORPI","Nordic Patent Institute",
"NTSC","Nordic Telcomm. Satellite Council",
"NWHF","Nordic World Heritage Foundation",
"NAFTA","North American FTA",
"NAPPO","N. Am. Plant Protection Org.",
"NASCO","North Atlantic Salmon Conserv. Org.",
"NATO","North Atlantic Treaty Org",
"NPAFC","North Pacific Anadromous Fish Commission",
"NPFSC","North Pacific Fur Seal Comm",
"NEAFC","Northeast Atlantic Fisheries Comm",
## O ####
"OASU","Pan-Am Union/Org of Am States",
"OMVG","Gambia River Basin Dev. Org.",
"OTIF","Central Office for Intl Railway Transport",
"OIVV","International Organization of Vine and Wine",
"OCAM","Common Afro-Malagasy Economic Org",
"OECD","Org for Econ Coop and Development",
"OAFU","Org for African Unity",
"OEEC","Org for European Economic Coop",
"OSCE","Org. Security Cooperation Europe",
"ORAIL","Org for the Collaboration of Railways",
"OMDKR","Org. Management & Dev. of Kaegara River",
"OAPEC","Org. Arab Petroleum Export. Countries",
"OCAS","Org. Central Am. States",
"OECS","Org. Eastern Caribbean States",
"OPEC","Org of Petroleum Exporting Countries",
"OISLC","Org. Islamic Conference",
"OSLO","Oslo Commission",
"OSPAR","OSPAR Commission",
## P ####
"PAFP","Pan-African Parliament",
"PANAL","Agency for Prohib. of Nuclear Arms in Latin Am.",
"PCAB","Pacific Cable-Board",
"PICES","North Pac. Marine Science Org.",
"PASIF","Pacific Island Forum",
"PLATA","Intergov. Committee of the River Plate Basin",
"PLAW","Intl Union for Protection of Lit & Art Works",
"PAIGH","Pan Am Instit of Geog & Hist",
"PAHO","Pan-Am Health Org",
"PAPU","Pan African Postal Union",
"PARIS","Paris Commission",
"PIPD","Partners in Population & Development",
"PAHC","Perm Assoc PanAm Highway Congresses",
"PCSP","Perm Comm for Conserv Maritime South Pacific",
"PCARB","Permanent Court of Arbitration",
"PIARC","World Road Assn",
"PIBAC","Perm Intl Bureau Analytical Chem-Human & Animal",
"PICS","Perm Intl Comm Studies Sanitary Equip",
"NARCO","Perm. Sec. of the S. Am. Agr. on Narcotic Drugs",
"PEDD","Pole European de Development",
"PMESA","Port Management Assoc. of E. and S. Africa",
"PUASP","Postal Union of Am, Spain, Port",
"PTSEA","Pref Trade Area: S & E Africa",
## Q ####
  ## R ####
"ROPAH","Intl Reg Org against Plant & Animal Disease",
"RADTU","Radiotelegraph Union",
"RASCO","Reg. Afr. Satellite Comm. Org.",
"RECSA","Regional Centre on Small Arms and Light Weapons",
"RCFC","Reg Commonwealth in the Field of Comm",
"REGCC","Regional Cooperation Council",
"RAELA","Reg. Council for Adult Educ. & Literacy in Africa",
"REPC","Reparation Commission",
"RIMMO","Reserve internationale medit. occidentale",
"RIOG","Rio Group",
## S ####
"SCAF","Scientific Council in SSA",
"SHCO","Shanghai Cooperation Organisation",
"SRDO","Senegal River Dev. Org.",
"SAMI","Societe arabe des mines de l'Inchiri",
"SWAPU","South & West Asia Postal Union",
"SACEP","S. Asia Coop. Environment Prog.",
"SAARC","South Asian Assoc Regional Coop",
"SITDE","South Investment, Trade & Tech. Data Exchg. Center",
"SPAC","South Pacific Comm",
"SEATO","Southeast Asia Treaty Organization",
"SEAME","Southeast Asian Minist. of Educ. Org.",
"SARTC","South African Regional Tourism Council",
"SACU","Southern African CU",
"SADC","Southern African Dev. Community",
"SADCC","Southern African Dev. Coordination Conf.",
"SWPD","Southwest Pacific Dialogue",
"SAAFA","Special Arab Aid Fund for Africa",
"SZCA","Suez Canal Admin",
"SUGU","Sugar Union",
"SUPCH","Superior Council of Health",
"SBLAC","Assoc. Superv. Banks of L/A & Caribb.",
"SCHEN","Group of Schengen",
"SEAFO","Int'l Commm. for SE Atlantic Fisheries",
"SEGIB","Ibero-American General Secretariat",
"SICA","Central American Integration System",
"SIECA","General Treaty on Cent Am Econ Integration",
"SPRCP","Intl Center Study Preserv & Restor Cultural Prop",
## T ####
"TCRMG","Tripartite Agreement for Monetary Gold",
"TURKC","Joint Admin. of Turkish Culture & Arts",
## U ####
"UDEAC","Central African Customs & Economic Union",
"UNIDR","Intl Instit for Unification of Private Law",
"UNFAO","Food & Ag Org",
"UNWHO","World Health Org",
"UNWMO","World Meteorological Org",
"UEMOA","West African Economic & Monetary Union",
"UIUCV","Union for Intl Use of Carriages & Vans",
"UMAC","Central African Monetary Union",
"UBEC","Union of Banana Exporting Countries",
"UMED","Union for the Mediterranean",
"UASC","United Arab Shipping Co.",
"UKDWD","UK Dominion Wool Disposals",
"UNAT","United Nations",
"UNESC","UN Education, Scientific, & Cultural Org",
"UNIDO","UN Industrial Development Org",
"UPUN","Universal Postal Union",
"USPAC","Univ. of South Pacific",
"UMOA","West African Monetary Union",
## V ####
"VALDI","Group of S. Hemisp. Countries on Env.",
"VASAB","Vision & Strategies Around Baltic Sea",
## W ####
"WCOMD","World Customs Org",
"WPACT","Warsaw Treaty Org",
"WASSA","Wassenaar Arrangement",
"WAEC","West Afr. Examinations Council",
"WAHC","West African Health Community",
"WAHO","West African Health Organization",
"WEUN","Western European Union",
"WNORF","West Nordic Fund",
"WCDC","Working Community of Danube Countries",
"WIPO","World Intell Prop Org",
"WTOUR","World Tourism Org.",
"WTOMC","World Trade Org"
## Y ####
  ## Z ####
  ## Other ####
)

